const admin = require('firebase-admin');
admin.initializeApp({ projectId: 'exam-coach-ai-platform' });
const db = admin.firestore();

const CPP_ID = 'Vs3aNmifAJc9bYRFCxXc';

const questions = [
    // ===== Domain I: Core Payroll Concepts (24%) — 22 questions =====
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Under the Common Law Test, which factor is most important in determining whether a worker is an employee or an independent contractor?',
        options: [
            'The degree of control the employer exercises over how the work is performed',
            'Whether the worker uses their own tools',
            'The length of the working relationship',
            'Whether the worker has a business license',
        ],
        correctAnswer: 0,
        explanation: 'The IRS Common Law Test focuses primarily on behavioral control — the degree to which the employer directs how, when, and where the work is performed. While tools, relationship duration, and business licenses are relevant factors, the core question is control. More control = more likely an employee.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Under the FLSA, which of the following is considered compensable time?',
        options: [
            'Waiting time when the employee is engaged to wait for the employer\'s benefit',
            'Commuting time from home to the regular workplace',
            'Bona fide meal periods of 30 minutes or more when the employee is completely relieved of duties',
            'Time spent in voluntary after-hours social events',
        ],
        correctAnswer: 0,
        explanation: 'Under the FLSA, "engaged to wait" is compensable — if the employer requires the employee to wait (e.g., on-call at the workplace), it is work time. Normal commuting is not compensable. Bona fide meal periods (completely relieved of duties) are not compensable. Voluntary social events outside work hours are not compensable.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'An employee earns $600 per week and works 48 hours. Under the FLSA, the minimum overtime payment for the 8 overtime hours is:',
        options: [
            '$180.00 (8 hours × $15.00 regular rate × 1.5)',
            '$120.00 (8 hours × $15.00)',
            '$240.00 (8 hours × $30.00)',
            '$150.00 (8 hours × $18.75)',
        ],
        correctAnswer: 0,
        explanation: 'The regular rate is $600 ÷ 40 hours = $15.00/hour. Overtime is 1.5× the regular rate: $15.00 × 1.5 = $22.50/hour. For 8 OT hours: 8 × $22.50 = $180.00. The total weekly pay would be $600 + $180 = $780. Always calculate the regular rate first, then apply the 1.5 multiplier.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'The current Social Security wage base determines:',
        options: [
            'The maximum amount of annual earnings subject to the Social Security (OASDI) tax',
            'The maximum amount subject to Medicare tax',
            'The minimum hourly wage under FLSA',
            'The maximum 401(k) contribution limit',
        ],
        correctAnswer: 0,
        explanation: 'The Social Security wage base is the annual maximum earnings subject to OASDI tax (6.2% employee/6.2% employer). Once wages exceed this amount, no additional Social Security tax is withheld. Medicare has no wage base limit — all earnings are subject to Medicare tax. The FLSA minimum wage and 401(k) limits are separate provisions.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Which federal form does an employee complete to claim withholding allowances and filing status for federal income tax?',
        options: [
            'Form W-4',
            'Form W-2',
            'Form I-9',
            'Form 941',
        ],
        correctAnswer: 0,
        explanation: 'Form W-4 (Employee\'s Withholding Certificate) is completed by the employee to indicate filing status, dependents, and additional withholding amounts. Form W-2 reports annual wages and taxes. Form I-9 verifies employment eligibility. Form 941 is the employer\'s quarterly federal tax return.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Backup withholding at 24% applies when:',
        options: [
            'A payee fails to provide a correct Taxpayer Identification Number (TIN) for reportable payments',
            'An employee requests additional withholding on Form W-4',
            'An employer cannot determine the employee\'s state of residence',
            'The employee\'s annual wages exceed the Social Security wage base',
        ],
        correctAnswer: 0,
        explanation: 'Backup withholding (currently 24%) applies to certain reportable payments (1099-type) when the payee fails to furnish a correct TIN, the IRS notifies the payer of an incorrect TIN, or the payee fails to certify they are not subject to backup withholding. It does not apply to regular W-2 wages, additional W-4 withholding, or Social Security wages.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Under the FLSA, which of the following white-collar exemptions requires a minimum salary threshold and a primary duty test?',
        options: [
            'Executive, administrative, and professional exemptions',
            'Only the executive exemption',
            'Only the computer employee exemption',
            'No exemptions require both salary and duties tests',
        ],
        correctAnswer: 0,
        explanation: 'The executive, administrative, and professional ("EAP") exemptions all require meeting both a salary basis/threshold test and a primary duties test. The executive must manage, direct employees, and have hiring/firing authority. The administrative must exercise independent judgment on significant matters. The professional must perform work requiring advanced knowledge.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'An employer provides group-term life insurance of $150,000 to an employee. The taxable imputed income is based on coverage exceeding:',
        options: [
            '$50,000',
            '$100,000',
            '$150,000',
            '$25,000',
        ],
        correctAnswer: 0,
        explanation: 'Under IRC Section 79, employer-provided group-term life insurance coverage up to $50,000 is tax-free. The cost of coverage exceeding $50,000 must be included as imputed income, calculated using the IRS Table I rates based on the employee\'s age. For $150,000 coverage, the imputed income is based on $100,000 of excess coverage.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'The Affordable Care Act (ACA) employer shared responsibility provision applies to applicable large employers (ALEs) with at least:',
        options: [
            '50 full-time employees or full-time equivalents',
            '100 full-time employees',
            '25 full-time employees',
            '500 full-time employees',
        ],
        correctAnswer: 0,
        explanation: 'Under the ACA, an ALE is an employer with 50 or more full-time employees (including full-time equivalents) in the prior calendar year. ALEs must offer affordable, minimum value health coverage to full-time employees or potentially face penalties. Full-time is defined as averaging 30+ hours per week.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Direct deposit via ACH requires the employer to initiate a transaction through:',
        options: [
            'The Originating Depository Financial Institution (ODFI)',
            'The Federal Reserve directly',
            'The employee\'s bank (RDFI) directly',
            'The Department of Labor',
        ],
        correctAnswer: 0,
        explanation: 'In the ACH process, the employer (originator) submits payment instructions to their ODFI (bank), which forwards them to the ACH operator (Federal Reserve or EPN), which routes them to the RDFI (employee\'s bank) for credit to the employee\'s account. The employer does not interact directly with the Federal Reserve, the employee\'s bank, or the DOL.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'A statutory employee is characterized by:',
        options: [
            'Being treated as an employee for FICA tax purposes but filing Schedule C for income tax',
            'Being exempt from all federal employment taxes',
            'Being treated as an independent contractor for all tax purposes',
            'Working exclusively for government agencies',
        ],
        correctAnswer: 0,
        explanation: 'Statutory employees (e.g., full-time life insurance salespeople, certain drivers, home workers) are treated as employees for FICA (Social Security and Medicare) tax purposes, but they report income and expenses on Schedule C (self-employment) for federal income tax. This hybrid status is specifically defined in IRC Section 3121(d).',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'The constructive receipt doctrine states that income is taxable when:',
        options: [
            'It is made available to the employee without substantial limitations, regardless of when actually received',
            'The employee physically receives the paycheck',
            'The employer records the expense in the general ledger',
            'The tax return is filed for the year',
        ],
        correctAnswer: 0,
        explanation: 'Constructive receipt means income is taxable when it is credited to the employee\'s account, set aside, or otherwise made available without substantial limitations — not necessarily when physically received. For example, a paycheck available on December 31 is taxable in that year even if the employee picks it up in January.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Under FLSA child labor provisions, 14- and 15-year-olds may NOT:',
        options: [
            'Work during school hours or in manufacturing or mining occupations',
            'Work in retail positions during non-school hours',
            'Perform light office work after school',
            'Work up to 3 hours on a school day',
        ],
        correctAnswer: 0,
        explanation: 'The FLSA restricts 14-15 year-olds from working during school hours and prohibits them from manufacturing, mining, and other hazardous occupations. They may work in retail, food service, and office settings during non-school hours, limited to 3 hours on school days and 8 hours on non-school days, with a maximum 18 hours during school weeks.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'FUTA tax is paid by:',
        options: [
            'The employer only — employees do not pay FUTA',
            'The employee only through payroll deductions',
            'Both the employer and employee equally',
            'The state unemployment agency',
        ],
        correctAnswer: 0,
        explanation: 'The Federal Unemployment Tax Act (FUTA) tax is an employer-only tax. Employees do not contribute to FUTA. The base FUTA rate is 6.0% on the first $7,000 of each employee\'s wages, but employers receive a credit of up to 5.4% for state unemployment taxes paid, resulting in an effective rate as low as 0.6%.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Gross-up is a calculation used when:',
        options: [
            'The employer pays the employee\'s tax liability on a benefit, making the benefit effectively tax-free to the employee',
            'The employee requests additional withholding on Form W-4',
            'The employer reduces an employee\'s gross pay due to overpayment',
            'The employer calculates overtime pay at 1.5 times the regular rate',
        ],
        correctAnswer: 0,
        explanation: 'Grossing up means the employer increases the taxable amount so that after taxes are withheld, the employee receives the intended net benefit. The formula accounts for federal, state, and FICA taxes. For example, if an employer wants to give an employee a $1,000 net bonus, the gross-up calculation determines the total gross amount needed so that $1,000 remains after all taxes.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'The Form I-9 must be completed:',
        options: [
            'By the end of the third business day after the employee\'s first day of work for pay',
            'Before the employee starts working',
            'Within 30 days of the employee\'s hire date',
            'Only when the employee is a non-citizen',
        ],
        correctAnswer: 0,
        explanation: 'Section 1 of Form I-9 must be completed by the employee no later than the first day of employment. Section 2 (employer verification of identity and work authorization documents) must be completed within 3 business days of the first day of work for pay. The I-9 is required for ALL employees regardless of citizenship status.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'IRC Section 125 cafeteria plans allow employees to:',
        options: [
            'Choose between taxable cash and qualified non-taxable benefits using pre-tax salary reductions',
            'Receive unlimited tax-free fringe benefits',
            'Defer all income taxes until retirement',
            'Exclude all wages from FICA taxes',
        ],
        correctAnswer: 0,
        explanation: 'Section 125 cafeteria plans let employees choose between taxable cash compensation and specific qualified benefits (health insurance, FSAs, dependent care) using pre-tax salary reductions. This reduces taxable income for both income tax and FICA (in most cases). Benefits are not unlimited — each has its own limits. Not all wages are excluded from FICA.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'The Additional Medicare Tax of 0.9% applies to:',
        options: [
            'Wages exceeding $200,000 for individual filers, withheld from the employee only',
            'All wages regardless of amount',
            'Wages exceeding the Social Security wage base',
            'Both employer and employee equally',
        ],
        correctAnswer: 0,
        explanation: 'The Additional Medicare Tax (0.9%) applies to wages exceeding $200,000 (single/$200,000 MFJ/$125,000 MFS). Employers must withhold the additional tax once wages exceed $200,000, regardless of filing status. There is no employer match for the Additional Medicare Tax — it is 100% employee-paid. The threshold is separate from the Social Security wage base.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'A tipped employee under the FLSA must receive a direct cash wage of at least:',
        options: [
            '$2.13 per hour, with tips making up the difference to the full federal minimum wage',
            'The full federal minimum wage with no tip credit',
            '$5.00 per hour regardless of tips received',
            'No minimum — tips are the sole compensation',
        ],
        correctAnswer: 0,
        explanation: 'Under the FLSA tip credit provision, employers may pay tipped employees a direct cash wage as low as $2.13/hour, provided the employee\'s tips bring total compensation to at least the federal minimum wage ($7.25/hour). If tips plus the direct wage do not reach the minimum wage, the employer must make up the difference. Some states require higher direct cash wages or no tip credit.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Supplemental wages include all of the following EXCEPT:',
        options: [
            'Regular hourly wages for hours worked during the standard workweek',
            'Bonuses',
            'Commissions',
            'Severance pay',
        ],
        correctAnswer: 0,
        explanation: 'Supplemental wages are compensation paid in addition to regular wages — including bonuses, commissions, overtime, severance pay, back pay, and retroactive increases. Regular hourly wages for standard hours are not supplemental. Supplemental wages may be taxed using a flat rate method (22% federal) or the aggregate method.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'An accountable plan for expense reimbursement must meet which conditions?',
        options: [
            'Business connection, adequate accounting, and return of excess amounts within a reasonable time',
            'Only that the employee submits receipts',
            'Only that expenses are under $500',
            'That the employer approves the expense after the fact',
        ],
        correctAnswer: 0,
        explanation: 'An accountable plan under IRS regulations requires three conditions: (1) business connection — expenses must have a business purpose; (2) adequate accounting — substantiation of expenses within a reasonable time; (3) return of excess — any excess reimbursement must be returned within a reasonable time. If these are not met, the plan is nonaccountable and reimbursements are taxable.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Core Payroll Concepts',
        stem: 'Form 941 is filed:',
        options: [
            'Quarterly by the employer to report wages paid, tips, and federal employment taxes',
            'Annually by the employee to report personal income',
            'Monthly by the employer to deposit FUTA taxes',
            'Semi-annually to report state unemployment taxes',
        ],
        correctAnswer: 0,
        explanation: 'Form 941 (Employer\'s Quarterly Federal Tax Return) is filed quarterly and reports total wages, tips, federal income tax withheld, and both employer and employee shares of Social Security and Medicare taxes. It is due by the last day of the month following the quarter end (April 30, July 31, October 31, January 31).',
        difficulty: 'Easy',
    },

    // ===== Domain II: Compliance/Research and Resources (16%) — 14 questions =====
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'Under federal wage garnishment provisions, the maximum amount that can be garnished from an employee\'s disposable earnings for ordinary creditor garnishments is:',
        options: [
            'The lesser of 25% of disposable earnings or the amount by which disposable earnings exceed 30 times the federal minimum wage',
            '50% of gross earnings',
            '15% of disposable earnings with no minimum wage test',
            '100% of earnings above the poverty line',
        ],
        correctAnswer: 0,
        explanation: 'Title III of the Consumer Credit Protection Act (CCPA) limits ordinary creditor garnishments to the lesser of: 25% of disposable earnings, or the amount by which disposable earnings exceed 30× the federal minimum hourly wage per week. Disposable earnings are gross pay minus legally required deductions (taxes, Social Security). Different limits apply to child support and tax levies.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'New hire reporting must be submitted to the state within how many days of the hire date under federal law?',
        options: [
            '20 days',
            '10 days',
            '30 days',
            '60 days',
        ],
        correctAnswer: 0,
        explanation: 'Federal law requires employers to report new hires to the state directory within 20 days of the hire date (or the first day of work for pay). Some states require earlier reporting. New hire reporting is used primarily to enforce child support obligations and detect fraud in public assistance programs.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'Unclaimed wages that cannot be returned to employees are subject to:',
        options: [
            'State escheatment (unclaimed property) laws requiring remittance to the state',
            'Return to the employer\'s general revenue permanently',
            'Donation to a charity of the employer\'s choice',
            'Automatic transfer to the employee\'s retirement account',
        ],
        correctAnswer: 0,
        explanation: 'Unclaimed or abandoned wages (uncashed paychecks, final pay) are subject to state escheatment laws. After a dormancy period (varies by state), the employer must report and remit the funds to the state\'s unclaimed property division. The employer cannot keep the funds, donate them, or redirect them. Employees can later claim the funds from the state.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'A child support income withholding order takes priority over which of the following?',
        options: [
            'Most other garnishments, including creditor garnishments',
            'Federal tax levies in all cases',
            'Nothing — it has the lowest priority',
            'Only voluntary deductions',
        ],
        correctAnswer: 0,
        explanation: 'Child support withholding orders generally take priority over most other garnishments, including creditor garnishments. The priority between child support and federal tax levies depends on which was received first in most cases. Child support can garnish up to 50-65% of disposable earnings, far more than the 25% limit for ordinary creditors.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'The penalty for failing to file Form W-2 with the SSA by the deadline depends on:',
        options: [
            'How late the filing is submitted — penalties increase the longer the delay',
            'The number of employees at the company',
            'The employee\'s filing status',
            'Whether the company is publicly traded',
        ],
        correctAnswer: 0,
        explanation: 'IRS penalties for late W-2 filing are tiered based on delay: a lower penalty if filed within 30 days of the deadline, a higher penalty if filed by August 1, and the maximum penalty for filing after August 1 or not filing at all. Intentional disregard carries even higher penalties. The amount per return increases with longer delays.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'Under the FMLA, an eligible employee is entitled to up to 12 weeks of unpaid leave for:',
        options: [
            'The birth or adoption of a child, or a serious health condition of the employee or immediate family member',
            'Vacation and personal time off',
            'Jury duty only',
            'Any reason the employee deems necessary',
        ],
        correctAnswer: 0,
        explanation: 'FMLA provides 12 weeks of unpaid, job-protected leave for qualifying reasons: birth/adoption/foster placement of a child, serious health condition of the employee, serious health condition of a spouse/child/parent, and qualifying exigencies related to military service. It does not cover vacation, general PTO, or any reason the employee chooses.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'A nonresident alien employee is generally subject to which federal income tax withholding rules?',
        options: [
            'Special NRA withholding rules that may include additional withholding and treaty-based exemptions',
            'The same rules as U.S. citizens with no differences',
            'No federal income tax withholding of any kind',
            'A flat 50% withholding rate on all compensation',
        ],
        correctAnswer: 0,
        explanation: 'Nonresident aliens (NRAs) are subject to special withholding rules. They generally cannot claim "married" status or the standard deduction on Form W-4, and may have additional withholding requirements. However, tax treaty benefits may reduce or eliminate withholding on certain types of income. Form 8233 is used to claim treaty exemptions for NRA employees.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'The IRS Trust Fund Recovery Penalty (TFRP) can be assessed against:',
        options: [
            'Any responsible person who willfully fails to collect, account for, or pay over employment taxes',
            'Only the company\'s CEO',
            'Only the payroll department manager',
            'The company as an entity but never individual employees',
        ],
        correctAnswer: 0,
        explanation: 'The TFRP (also called the 100% penalty) can be assessed against any person who is responsible for collecting, accounting for, or paying over trust fund taxes (employee withholding) and who willfully fails to do so. "Responsible persons" can include officers, directors, payroll managers, bookkeepers, or anyone with authority over the company\'s finances.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'Federal tax deposits must be made electronically using:',
        options: [
            'EFTPS (Electronic Federal Tax Payment System)',
            'Paper check mailed to the IRS',
            'Cash payment at a local bank',
            'Wire transfer directly to the U.S. Treasury',
        ],
        correctAnswer: 0,
        explanation: 'All federal tax deposits must be made electronically using EFTPS (Electronic Federal Tax Payment System). Employers must enroll in EFTPS and schedule deposits in advance. Paper checks, cash payments, and direct wire transfers are not accepted for employment tax deposits. Penalties apply for failure to deposit electronically.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'Under multi-state taxation, when an employee works in multiple states, income tax withholding is generally required by:',
        options: [
            'Each state where the employee performs services, based on that state\'s rules',
            'Only the state where the employer is headquartered',
            'Only the employee\'s state of residence',
            'The federal government consolidates all state withholding',
        ],
        correctAnswer: 0,
        explanation: 'When an employee works in multiple states, each work state may require income tax withholding based on the wages earned there. Some states have reciprocal agreements that simplify this. The state of residence may also require withholding or credit for taxes paid to other states. Each state\'s rules determine the withholding obligation.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'Form W-2 must be furnished to employees by:',
        options: [
            'January 31 of the following year',
            'March 15 of the following year',
            'April 15 of the following year',
            'The last day of February of the following year',
        ],
        correctAnswer: 0,
        explanation: 'Employers must furnish Form W-2 to employees by January 31 of the year following the reporting year. The same January 31 deadline applies for filing W-2s with the Social Security Administration. Late filing results in penalties that increase based on delay.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'Tax equalization for expatriate employees means:',
        options: [
            'The employee pays the same amount of tax as if they had stayed in their home country',
            'All taxes are eliminated for employees working abroad',
            'The employee pays taxes in both the home and host country at full rates',
            'The employer does not withhold any taxes on expatriate wages',
        ],
        correctAnswer: 0,
        explanation: 'Tax equalization ensures an expatriate employee is no better or worse off tax-wise than if they had remained in their home country. The employer calculates a "hypothetical tax" (what the employee would have paid at home) and the employer pays any additional tax liability in the host country. This prevents tax outcomes from influencing assignment decisions.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'Employers must retain Form I-9 for terminated employees for:',
        options: [
            'The later of 3 years after the hire date or 1 year after the termination date',
            'Permanently',
            '7 years after the termination date',
            '90 days after the termination date',
        ],
        correctAnswer: 0,
        explanation: 'I-9 retention requirement is the later of: 3 years after the date of hire, or 1 year after the date employment ends. For example, if an employee works for 5 years, the I-9 must be retained for 1 year after termination (since that exceeds 3 years after hire). After the retention period, I-9s should be securely destroyed.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Compliance and Research',
        stem: 'COBRA continuation coverage must be offered to qualified beneficiaries for:',
        options: [
            '18 months for most qualifying events, with extensions up to 36 months for certain events',
            '6 months for all qualifying events',
            '12 months regardless of the qualifying event',
            'Indefinitely until the beneficiary obtains new coverage',
        ],
        correctAnswer: 0,
        explanation: 'COBRA coverage duration depends on the qualifying event: 18 months for termination or reduction in hours (extendable to 29 months for disability). Divorce, death, or dependent aging out qualifies for 36 months. The beneficiary pays up to 102% of the full premium. COBRA applies to employers with 20+ employees.',
        difficulty: 'Medium',
    },

    // ===== Domain III: Calculation of the Paycheck (20%) — 18 questions =====
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'An employee receives a $5,000 bonus as supplemental wages. If the employer uses the flat rate method, federal income tax withholding is:',
        options: [
            '$1,100 (22% of $5,000)',
            '$1,200 (24% of $5,000)',
            '$750 (15% of $5,000)',
            '$500 (10% of $5,000)',
        ],
        correctAnswer: 0,
        explanation: 'The optional flat rate for supplemental wages is 22% (for supplemental wages up to $1 million in a calendar year). For $5,000: $5,000 × 0.22 = $1,100. If supplemental wages exceed $1 million, the excess is withheld at 37%. Alternatively, the employer may use the aggregate method, combining regular and supplemental wages.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'When calculating disposable earnings for garnishment purposes, which deductions are subtracted from gross pay?',
        options: [
            'Only legally required deductions: federal, state, and local taxes, and Social Security/Medicare',
            'All deductions including voluntary benefits, 401(k), and union dues',
            'Only federal income tax withholding',
            'No deductions — disposable earnings equal gross pay',
        ],
        correctAnswer: 0,
        explanation: 'Disposable earnings = gross pay minus legally required deductions (federal/state/local income tax, Social Security, Medicare, and any state disability or unemployment deductions required by law). Voluntary deductions (401(k), health insurance, union dues) are NOT subtracted when calculating disposable earnings for garnishment purposes.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'An employee earns $10/hour and works 45 hours in a workweek. The employee also has a $100 nondiscretionary bonus for the week. What is the regular rate of pay?',
        options: [
            '$12.22 ($500 + $100 = $600 ÷ 45 hours)',
            '$10.00 (base hourly rate only)',
            '$11.11 ($500 ÷ 45 hours)',
            '$13.33 ($600 ÷ 45 hours rounded up)',
        ],
        correctAnswer: 0,
        explanation: 'The regular rate includes all remuneration for hours worked — including nondiscretionary bonuses. Total earnings: ($10 × 45 = $450 straight time) + $100 bonus = $550... wait. Actually: $10 × 45 = $450 straight time plus $100 bonus = $550. But regular rate = total compensation ÷ total hours = ($450 + $100) / 45 = $12.22. The OT premium is half the regular rate × OT hours: $6.11 × 5 = $30.56.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'Third-party sick pay is:',
        options: [
            'Payments made by an insurance company or other third party to an employee for periods of sickness or injury',
            'Regular wages paid by the employer during sick leave',
            'Government disability benefits from Social Security',
            'Workers\' compensation payments for on-the-job injuries',
        ],
        correctAnswer: 0,
        explanation: 'Third-party sick pay (TPSP) is paid by an entity other than the employer (typically an insurance carrier) to employees who are absent due to sickness or injury. TPSP is subject to federal income tax and FICA (for the first 6 months). Employer-paid sick leave is regular wages. SSDI and workers\' comp have different tax treatments.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'The aggregate method of withholding supplemental wages involves:',
        options: [
            'Combining supplemental and regular wages into one total and withholding tax on the combined amount using the W-4 information',
            'Withholding at a flat 22% on all supplemental wages',
            'Exempting supplemental wages from all withholding',
            'Withholding at the employee\'s marginal tax rate determined by the IRS',
        ],
        correctAnswer: 0,
        explanation: 'The aggregate method adds supplemental wages to the regular wages for the pay period, calculates withholding on the combined total using the employee\'s W-4 information and the standard tax tables, then subtracts the tax already withheld on regular wages. The difference is the supplemental wage withholding. This method may result in higher or lower withholding than the flat 22% method.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'An employee\'s pre-tax 401(k) contribution reduces taxable wages for:',
        options: [
            'Federal and state income tax, but NOT Social Security and Medicare (FICA)',
            'Federal income tax, state income tax, and all FICA taxes',
            'Only federal income tax',
            'No taxes — 401(k) contributions are fully taxable',
        ],
        correctAnswer: 0,
        explanation: 'Traditional pre-tax 401(k) contributions reduce wages subject to federal and most state income taxes but remain subject to FICA (Social Security and Medicare) taxes. This means 401(k) contributions lower current income tax but do not reduce FICA withholding. Roth 401(k) contributions are made after all taxes.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'An overpayment to an employee can be recovered by the employer through:',
        options: [
            'Payroll deductions in subsequent pay periods, subject to state wage payment laws and employee notification',
            'Reducing the employee\'s future vacation accrual without notice',
            'Filing a lawsuit immediately without attempting recovery',
            'Deducting the full amount from the next paycheck regardless of minimum wage protections',
        ],
        correctAnswer: 0,
        explanation: 'Overpayment recovery must follow state wage payment laws, which vary. Most require written notice to the employee, a reasonable recovery schedule, and may prohibit reducing pay below minimum wage. The employer should document the overpayment, notify the employee, and arrange a recovery plan. Some states require employee consent for deductions.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'Personal use of a company vehicle is:',
        options: [
            'A taxable fringe benefit that must be included in the employee\'s income',
            'Always tax-free regardless of usage',
            'Taxable only if the vehicle costs over $50,000',
            'Deductible by the employee on their personal tax return',
        ],
        correctAnswer: 0,
        explanation: 'Personal use of a company vehicle is a taxable fringe benefit. The value must be included in the employee\'s wages and is subject to income tax, Social Security, and Medicare. Employers can use several IRS valuation methods: Annual Lease Value, Cents-per-Mile, or the Commuting Rule. Only qualified nonpersonal use vehicles (police cars, ambulances) are exempt.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'The IRS special accounting rule for fringe benefits allows employers to:',
        options: [
            'Treat the value of benefits provided in the last two months of the year as paid in the following year',
            'Defer all fringe benefit taxation indefinitely',
            'Exclude all fringe benefits from Form W-2 reporting',
            'Report fringe benefits only when the employee terminates',
        ],
        correctAnswer: 0,
        explanation: 'The special accounting rule allows employers to treat taxable noncash fringe benefits provided during November and December as paid in the following calendar year for reporting and withholding purposes. This simplifies year-end processing but must be applied consistently. It does not defer taxation indefinitely or exclude benefits from reporting.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'When an employee dies, wages paid to the estate or beneficiary in the same calendar year of death are:',
        options: [
            'Not subject to federal income tax withholding but are subject to FICA taxes',
            'Subject to all regular payroll taxes including FIT',
            'Completely tax-free',
            'Subject to federal income tax but exempt from FICA',
        ],
        correctAnswer: 0,
        explanation: 'Wages paid in the same calendar year as the employee\'s death to the estate or beneficiary are subject to Social Security and Medicare taxes (FICA) but not federal income tax withholding. They are reported on Form W-2 (for FICA) and Form 1099-MISC (for the income amount). Wages paid in the year following death are exempt from FICA and reported only on Form 1099-MISC.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'Qualified transportation benefits under IRC Section 132(f) include:',
        options: [
            'Transit passes, vanpooling, and qualified parking up to monthly exclusion limits',
            'Personal vehicle gas reimbursements with no limit',
            'Airline tickets for business travel',
            'Hotel accommodations for commuting employees',
        ],
        correctAnswer: 0,
        explanation: 'IRC Section 132(f) allows employers to provide tax-free qualified transportation fringe benefits: transit passes, vanpool benefits, and qualified parking, each up to monthly exclusion limits set annually. Gas reimbursements for personal commuting, airline tickets, and hotel stays are not qualified transportation benefits under Section 132(f).',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'An employer depositing over $100,000 in employment taxes on any day during the deposit period must deposit by:',
        options: [
            'The next banking day',
            'The following Friday',
            'Within 3 business days',
            'The 15th of the following month',
        ],
        correctAnswer: 0,
        explanation: 'The $100,000 next-day deposit rule: if an employer accumulates $100,000 or more in employment taxes on any day during a deposit period, the taxes must be deposited by the next banking day. This overrides the employer\'s regular deposit schedule (monthly or semi-weekly). The employer also becomes a semi-weekly depositor for the remainder of the year and the following year.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'Employer-provided educational assistance is tax-free up to:',
        options: [
            '$5,250 per year under IRC Section 127',
            '$10,000 per year',
            'Any amount with no limit',
            '$2,500 per semester',
        ],
        correctAnswer: 0,
        explanation: 'Under IRC Section 127, employers can provide up to $5,250 per calendar year in educational assistance benefits tax-free. This includes tuition, fees, books, and supplies. The assistance need not be job-related. Amounts exceeding $5,250 are taxable unless they qualify as a working condition fringe benefit (job-related education under Section 132).',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'Stock options are generally taxable to the employee:',
        options: [
            'At the time of exercise for nonqualified stock options (NQSOs), based on the spread between exercise price and fair market value',
            'At the time the options are granted',
            'Only when the stock is eventually sold',
            'Stock options are never taxable',
        ],
        correctAnswer: 0,
        explanation: 'For NQSOs, the taxable event occurs at exercise — the spread (FMV minus exercise price) is treated as compensation subject to income tax, Social Security, and Medicare. The employer must report and withhold accordingly. Incentive Stock Options (ISOs) have different rules — generally no tax at exercise (though AMT may apply), with taxation at sale.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'Net pay is calculated as:',
        options: [
            'Gross pay minus all deductions (taxes, voluntary deductions, and involuntary deductions)',
            'Gross pay minus federal income tax only',
            'Total hours worked multiplied by the hourly rate',
            'Gross pay plus employer contributions',
        ],
        correctAnswer: 0,
        explanation: 'Net pay (take-home pay) = gross pay minus all deductions: federal/state/local income tax, Social Security, Medicare, voluntary deductions (401(k), health insurance, FSA), and involuntary deductions (garnishments, tax levies, child support). It does not include employer-paid taxes or contributions, which are separate from the employee\'s pay.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'The fluctuating workweek method of overtime calculation requires:',
        options: [
            'A fixed salary covering all hours worked with overtime paid at half-time (0.5×) the calculated regular rate',
            'A variable salary that changes based on hours worked',
            'Overtime paid at 1.5× the regular rate plus a shift differential',
            'No overtime payment regardless of hours worked',
        ],
        correctAnswer: 0,
        explanation: 'Under the fluctuating workweek method (FWW), the employee receives a fixed salary for all hours worked each week. The regular rate fluctuates based on total hours (salary ÷ hours). Since the salary already covers all hours at straight time, overtime is paid at half-time (0.5×) the regular rate for hours over 40. The employee must clearly understand and agree to this arrangement.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Calculation of the Paycheck',
        stem: 'Allocated tips on Form W-2 apply when:',
        options: [
            'A large food or beverage establishment\'s employees report tips below 8% of the establishment\'s gross receipts',
            'Any employee receives cash tips over $20 per month',
            'The employer provides a tip pool for all employees',
            'Tips are paid through credit card transactions only',
        ],
        correctAnswer: 0,
        explanation: 'Tip allocation is required for large food or beverage establishments (those with more than 10 employees) when total tips reported by employees are less than 8% of the establishment\'s gross receipts. Allocated tips are reported in Box 8 of Form W-2 but are not subject to withholding. The $20/month threshold triggers regular tip reporting, not allocation.',
        difficulty: 'Hard',
    },

    // ===== Domain IV: Payroll Process and Supporting Systems (12%) — 11 questions =====
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'A payroll system\'s master file typically contains:',
        options: [
            'Employee demographics, pay rates, tax withholding elections, deduction codes, and direct deposit information',
            'Only the employee\'s name and Social Security number',
            'Only information needed for the current pay period',
            'Historical payroll data exclusively',
        ],
        correctAnswer: 0,
        explanation: 'The master file is the foundation of the payroll system, containing standing data used each pay cycle: employee demographics, tax elections (W-4 data), pay rates, benefit deductions, direct deposit routing, work location, job classifications, and more. It contains both current and historical data and is updated when employee information changes.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'Employee self-service (ESS) portals benefit the payroll department by:',
        options: [
            'Reducing manual data entry by allowing employees to update personal information, view pay stubs, and access W-2s',
            'Eliminating the need for payroll staff entirely',
            'Automatically calculating overtime without payroll review',
            'Bypassing all internal controls on data changes',
        ],
        correctAnswer: 0,
        explanation: 'ESS portals enable employees to update addresses, direct deposit, tax withholding, and view/print pay stubs and W-2s — reducing manual data entry, phone calls, and paperwork for payroll staff. They do not eliminate the need for payroll professionals, automatically calculate complex pay, or bypass controls. Proper ESS systems include audit trails and approval workflows.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'A business continuity plan (BCP) for payroll should include:',
        options: [
            'Alternative processing methods, communication plans, data backup procedures, and recovery time objectives',
            'Only a list of emergency phone numbers',
            'Only instructions for manual check writing',
            'A plan to suspend all payroll operations until the emergency ends',
        ],
        correctAnswer: 0,
        explanation: 'A comprehensive payroll BCP ensures employees are paid even during disruptions. It includes alternative processing methods (backup vendors, manual procedures), communication plans (notifying employees and banks), data backup and recovery procedures, recovery time objectives, and testing schedules. Suspending payroll is not an option — employees must be paid on time.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'When selecting a new payroll system, a Request for Proposal (RFP) should include:',
        options: [
            'Detailed business requirements, current pain points, integration needs, timeline, and evaluation criteria',
            'Only the company name and contact information',
            'The vendor\'s proposed solution before requirements are defined',
            'A request for the lowest price with no functional specifications',
        ],
        correctAnswer: 0,
        explanation: 'An effective RFP clearly communicates the organization\'s needs to potential vendors: business requirements, current challenges, integration points (GL, HR, benefits), compliance needs, timeline, budget constraints, and evaluation criteria. This enables vendors to propose targeted solutions. Without detailed requirements, proposals cannot be meaningfully compared.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'Parallel testing during a payroll system implementation involves:',
        options: [
            'Running both the old and new systems simultaneously to compare results and verify accuracy',
            'Testing the new system in isolation without comparison',
            'Having two different teams process payroll independently',
            'Running the new system at double speed to test performance',
        ],
        correctAnswer: 0,
        explanation: 'Parallel testing runs the existing and new payroll systems at the same time for one or more pay cycles, comparing results to ensure the new system produces accurate output. Discrepancies are investigated and resolved before the old system is decommissioned. This is the most thorough testing method but also the most resource-intensive.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'System security for payroll data should include:',
        options: [
            'Role-based access controls, encryption, audit trails, and regular security assessments',
            'Giving all employees full access to payroll data for transparency',
            'Storing data without encryption since it is internal',
            'Relying exclusively on the vendor\'s default security settings',
        ],
        correctAnswer: 0,
        explanation: 'Payroll data contains sensitive PII (SSNs, bank accounts, salaries) requiring robust security: role-based access controls limit who sees what, encryption protects data in transit and at rest, audit trails track who accessed or changed data, and regular assessments identify vulnerabilities. Universal access violates confidentiality. Default settings may not meet organizational requirements.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'Batch processing in payroll refers to:',
        options: [
            'Collecting and processing all payroll transactions together at scheduled intervals',
            'Processing each payroll transaction individually in real time',
            'Running payroll only once per year',
            'Sending all employee paychecks in a single envelope',
        ],
        correctAnswer: 0,
        explanation: 'Batch processing collects all payroll transactions (time records, deductions, adjustments) and processes them together as a group at scheduled times (e.g., each pay period). This is efficient for high-volume processing. Real-time processing handles transactions individually as they occur. Batch totals are used to verify accuracy of the processed group.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'Data mapping during a payroll system conversion is necessary to:',
        options: [
            'Ensure data fields from the old system correctly transfer to corresponding fields in the new system',
            'Delete all historical data before starting the new system',
            'Create new employee records from scratch',
            'Eliminate the need for data validation after conversion',
        ],
        correctAnswer: 0,
        explanation: 'Data mapping defines how each data field in the old system corresponds to fields in the new system. Proper mapping ensures accurate transfer of employee records, pay history, tax data, and deductions. Historical data is typically preserved (not deleted). Existing records are migrated (not recreated). Data validation after conversion is still essential.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'Positive pay is a banking fraud prevention feature that:',
        options: [
            'Matches issued check details against presented checks and rejects mismatches',
            'Automatically deposits funds into employee accounts',
            'Guarantees all checks will clear regardless of account balance',
            'Prevents employees from cashing checks at non-partner banks',
        ],
        correctAnswer: 0,
        explanation: 'Positive pay is a fraud prevention service where the employer sends the bank a file of issued checks (check numbers, amounts, dates, payees). When checks are presented for payment, the bank matches them against the file. Mismatches (altered amounts, forged checks) are flagged for the employer to approve or reject, preventing fraudulent check cashing.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'A payroll system interface with the general ledger ensures:',
        options: [
            'Payroll transactions are automatically posted to the correct GL accounts for financial reporting',
            'Employee pay stubs are printed from the GL system',
            'The GL system calculates payroll taxes',
            'Time and attendance data is collected by the GL',
        ],
        correctAnswer: 0,
        explanation: 'The payroll-to-GL interface automatically transfers payroll journal entries (wages, taxes, deductions, employer costs) to the appropriate general ledger accounts. This ensures accurate financial reporting without manual journal entry creation. The GL does not calculate taxes, print pay stubs, or collect time data — those are payroll system functions.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Process and Systems',
        stem: 'User acceptance testing (UAT) in a payroll system implementation is performed by:',
        options: [
            'End users (payroll staff) to verify the system meets business requirements before go-live',
            'The software vendor exclusively',
            'The IT department without payroll input',
            'External auditors',
        ],
        correctAnswer: 0,
        explanation: 'UAT is the final testing phase performed by actual payroll users to validate that the system meets their business requirements and workflows. It occurs after the vendor\'s unit testing and IT\'s integration testing. Payroll staff test real-world scenarios — pay calculations, tax withholding, deductions, reporting — and confirm the system is ready for production.',
        difficulty: 'Easy',
    },

    // ===== Domain V: Payroll Administration and Management (10%) — 9 questions =====
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Administration and Management',
        stem: 'A service level agreement (SLA) between the payroll department and other business units should define:',
        options: [
            'Expected service standards, response times, responsibilities, and escalation procedures',
            'Only the payroll processing schedule',
            'The payroll department\'s annual budget',
            'Individual employee performance ratings',
        ],
        correctAnswer: 0,
        explanation: 'An SLA formalizes the relationship between payroll and its internal customers — defining what services are provided, performance standards (accuracy, timeliness), response times for inquiries, mutual responsibilities (e.g., timely submission of time records), and escalation procedures when issues arise. It sets expectations and accountability for both parties.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Administration and Management',
        stem: 'Benchmarking payroll operations involves:',
        options: [
            'Comparing the department\'s performance metrics against industry standards or best practices',
            'Setting the department budget equal to last year\'s spending',
            'Hiring the same number of staff as competitors',
            'Using the same payroll software as the largest company in the industry',
        ],
        correctAnswer: 0,
        explanation: 'Benchmarking compares key payroll metrics (cost per payroll payment, error rates, time to process, staff-to-employee ratios) against industry standards, peer organizations, or best-practice targets. It identifies improvement opportunities and justifies resource requests. It is not about copying competitors\' headcount, software, or budgets.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Administration and Management',
        stem: 'Effective delegation in the payroll department requires:',
        options: [
            'Clear communication of expectations, authority to complete the task, and accountability for results',
            'Assigning tasks without any instructions or follow-up',
            'Only delegating routine tasks and never complex ones',
            'Retaining all decision-making authority while assigning the work',
        ],
        correctAnswer: 0,
        explanation: 'Effective delegation involves clearly communicating the task, expectations, and deadlines; granting the authority needed to complete the work; providing necessary resources and training; and holding the person accountable for results while providing support. Delegation without guidance sets people up to fail. Retaining all authority defeats the purpose.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Administration and Management',
        stem: 'When a payroll department receives a government agency notice regarding a discrepancy, the first step should be:',
        options: [
            'Review the notice carefully, research the issue, and respond within the required timeframe',
            'Ignore the notice until a second notice is received',
            'Pay any amount demanded immediately without verification',
            'Forward the notice to the employee without review',
        ],
        correctAnswer: 0,
        explanation: 'Government notices require prompt, careful attention. The payroll professional should read the notice thoroughly, understand what is being requested, research the discrepancy (compare records, verify calculations), and respond within the stated deadline. Ignoring notices leads to penalties. Paying without verification may waste money. Forwarding to employees is not appropriate for employer obligations.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Administration and Management',
        stem: 'Payroll department procedures documentation is important because it:',
        options: [
            'Ensures consistency, supports training, and provides a reference for audits and business continuity',
            'Is required only for companies with over 10,000 employees',
            'Replaces the need for trained payroll staff',
            'Is only useful during the initial system implementation',
        ],
        correctAnswer: 0,
        explanation: 'Documented procedures ensure consistent processing regardless of who performs the work, support training of new staff, provide evidence of controls for internal and external audits, and are critical for business continuity if key personnel are unavailable. Documentation is valuable for organizations of all sizes and must be maintained and updated regularly.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Administration and Management',
        stem: 'A payroll shared services model centralizes payroll processing to:',
        options: [
            'Achieve economies of scale, standardize processes, and improve consistency across business units',
            'Eliminate all local compliance requirements',
            'Reduce employee headcount by 90% immediately',
            'Remove the need for payroll expertise',
        ],
        correctAnswer: 0,
        explanation: 'Shared services centralizes repetitive payroll processing to gain efficiency, standardize procedures, leverage technology, and ensure consistent treatment across locations. Local compliance requirements still apply and must be managed within the shared service. While staffing may be optimized, drastic immediate reductions are unrealistic. Payroll expertise remains essential.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Administration and Management',
        stem: 'Effective customer service in the payroll department includes:',
        options: [
            'Responding to employee inquiries accurately, promptly, and with empathy while maintaining confidentiality',
            'Sharing an employee\'s payroll details with their coworkers to resolve disputes faster',
            'Telling employees to figure out their pay stubs on their own',
            'Responding only to written complaints submitted through formal channels',
        ],
        correctAnswer: 0,
        explanation: 'Payroll customer service requires accuracy (correct answers), timeliness (prompt response), empathy (understanding employee concerns about pay), and confidentiality (never sharing one employee\'s information with another). Payroll affects employees\' livelihoods, making trust and responsiveness essential. Multiple channels (phone, email, self-service) should be available.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Administration and Management',
        stem: 'A payroll skills assessment for staff development should evaluate:',
        options: [
            'Technical payroll knowledge, compliance awareness, system proficiency, and soft skills',
            'Only the number of years of payroll experience',
            'Only whether the employee has a CPP certification',
            'Only the employee\'s typing speed',
        ],
        correctAnswer: 0,
        explanation: 'A comprehensive skills assessment evaluates multiple dimensions: technical knowledge (tax calculations, wage and hour law), compliance awareness (regulatory updates, filing requirements), system proficiency (payroll software, reporting tools), and soft skills (communication, problem-solving, customer service). Experience, certification, and technical skills are all factors but none alone is sufficient.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Payroll Administration and Management',
        stem: 'Setting departmental objectives for the payroll department should align with:',
        options: [
            'The organization\'s overall strategic goals and key performance indicators',
            'Only the payroll manager\'s personal preferences',
            'Whatever the previous year\'s objectives were, unchanged',
            'Industry benchmarks without considering the organization\'s specific needs',
        ],
        correctAnswer: 0,
        explanation: 'Departmental objectives should cascade from the organization\'s strategic goals. If the company prioritizes cost reduction, payroll objectives might focus on processing efficiency. If compliance is the focus, accuracy and audit readiness take priority. Objectives should be specific, measurable, and aligned with organizational direction — not based on personal preference or rote repetition.',
        difficulty: 'Medium',
    },

    // ===== Domain VI: Audits (9%) — 8 questions =====
    {
        examId: CPP_ID, type: 'mcq', domain: 'Audits',
        stem: 'Segregation of duties in payroll means:',
        options: [
            'Dividing payroll responsibilities so that no single person controls the entire process from input to payment',
            'Having one person handle all payroll functions for efficiency',
            'Separating payroll processing from the pay schedule',
            'Assigning all audit functions to the payroll department',
        ],
        correctAnswer: 0,
        explanation: 'Segregation of duties is a key internal control: different people should handle payroll input (time entry), processing (calculations), approval (review), and payment (distribution). This prevents any single person from creating fictitious employees, altering pay rates, and issuing unauthorized payments undetected. It is a fundamental fraud prevention control.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Audits',
        stem: 'A payroll reconciliation should compare:',
        options: [
            'The current period\'s payroll register totals to the prior period and investigate significant variances',
            'Only the bank statement to the payroll register',
            'Employee names to the company directory',
            'The payroll budget to the training budget',
        ],
        correctAnswer: 0,
        explanation: 'Period-to-period reconciliation compares current payroll totals (gross pay, taxes, deductions, net pay, headcount) to the prior period and investigates significant variances. This catches errors, unauthorized changes, and anomalies. Bank reconciliation, employee verification, and budget comparison are separate but complementary controls.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Audits',
        stem: 'Sarbanes-Oxley (SOX) compliance for payroll requires:',
        options: [
            'Documented internal controls over financial reporting, including payroll processes that affect financial statements',
            'External audit of every individual paycheck',
            'Government approval before each payroll run',
            'Mandatory use of a specific payroll software vendor',
        ],
        correctAnswer: 0,
        explanation: 'SOX Section 404 requires public companies to document and test internal controls over financial reporting. Payroll is a significant component of financial statements (wages, taxes, accruals). Controls must be documented, tested, and audited. SOX does not mandate specific software, government pre-approval, or individual check auditing.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Audits',
        stem: 'Accumulator balancing involves:',
        options: [
            'Verifying that year-to-date and quarter-to-date totals match the sum of individual period amounts',
            'Counting the number of employees on the payroll',
            'Balancing the payroll checking account',
            'Comparing employee headcount across departments',
        ],
        correctAnswer: 0,
        explanation: 'Accumulator balancing verifies that running totals (YTD gross pay, YTD taxes, QTD wages) equal the sum of all individual period amounts. Out-of-balance accumulators can cause incorrect W-2 reporting, tax deposit errors, and compliance issues. This should be done regularly (each pay period) and is especially critical before quarterly and annual filings.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Audits',
        stem: 'An audit trail in payroll systems tracks:',
        options: [
            'Who made changes, what was changed, when the change occurred, and the before/after values',
            'Only the final payroll output',
            'Only unsuccessful login attempts',
            'The physical location of paper checks',
        ],
        correctAnswer: 0,
        explanation: 'A comprehensive audit trail captures all changes to payroll data: the user who made the change, what field was modified, the date and time of the change, and the old and new values. This supports fraud detection, error investigation, and compliance audits. It covers data input, processing, and output — not just final results or security events.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Audits',
        stem: 'Quarterly reconciliation of Form 941 should verify that:',
        options: [
            'Total wages, tips, and taxes reported match the payroll register totals and tax deposits made',
            'Only the check numbers match the bank statement',
            'Employee vacation balances are accurate',
            'The general ledger reflects the correct fiscal year',
        ],
        correctAnswer: 0,
        explanation: 'Form 941 reconciliation compares reported wages and tips to payroll register totals, verifies tax calculations (FIT, Social Security, Medicare), and confirms that deposits made via EFTPS match the liability. Discrepancies may indicate processing errors, missed adjustments, or unreported wages. This is a critical compliance control performed each quarter.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Audits',
        stem: 'A ghost employee fraud scheme is best detected by:',
        options: [
            'Comparing the payroll register to the HR employee master file and verifying active status',
            'Increasing all employee pay rates by the same percentage',
            'Eliminating direct deposit and paying only by check',
            'Reducing the payroll processing frequency',
        ],
        correctAnswer: 0,
        explanation: 'Ghost employees are fictitious workers added to the payroll by someone with system access. Comparing the payroll register to the HR master file (and verifying employees are real and active) is the primary detection method. Additional controls include physical paycheck distribution, address analysis (multiple employees at same address), and random audits of new hires.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Audits',
        stem: 'Reconciling payroll output to external vendors (such as 401(k) providers) ensures:',
        options: [
            'Employee contribution amounts transmitted match the amounts deducted from paychecks',
            'The vendor\'s investment returns match payroll projections',
            'All employees are enrolled in the same investment fund',
            'The vendor\'s billing matches the payroll department\'s budget',
        ],
        correctAnswer: 0,
        explanation: 'External vendor reconciliation verifies that the amounts deducted from employee paychecks for benefits (401(k), FSA, HSA, garnishments) match the amounts transmitted to and received by the vendors. Discrepancies can mean missed contributions, over-deductions, or transmission errors — all of which affect employees and compliance.',
        difficulty: 'Medium',
    },

    // ===== Domain VII: Accounting (9%) — 8 questions =====
    {
        examId: CPP_ID, type: 'mcq', domain: 'Accounting',
        stem: 'A payroll journal entry for recording gross wages paid would include:',
        options: [
            'A debit to wages/salary expense and credits to various liability accounts (taxes payable, deductions payable) and cash/bank',
            'A credit to wages expense and a debit to cash',
            'Only a debit to cash for the net pay amount',
            'A debit to accounts receivable and credit to revenue',
        ],
        correctAnswer: 0,
        explanation: 'The payroll journal entry debits wage/salary expense (the total gross pay cost) and credits: tax liability accounts (FIT payable, FICA payable, state tax payable), deduction liability accounts (401(k) payable, benefits payable), and cash/bank (net pay). Debits increase expenses; credits increase liabilities. The entry must balance — total debits equal total credits.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Accounting',
        stem: 'Payroll accruals are recorded to:',
        options: [
            'Recognize wages earned by employees but not yet paid as of the reporting period end date',
            'Reduce the company\'s tax liability',
            'Increase cash on the balance sheet',
            'Eliminate the need for year-end adjustments',
        ],
        correctAnswer: 0,
        explanation: 'Under accrual accounting, wages earned but not yet paid must be recognized as an expense and a liability in the period they are earned — regardless of when payment occurs. For example, if the pay period crosses a month-end, the wages for days worked in the old month must be accrued. Accruals are typically reversed in the next period when payment is made.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Accounting',
        stem: 'The matching principle in accounting requires:',
        options: [
            'Expenses to be recorded in the same period as the revenue they help generate',
            'All payments to be made on the same day they are recorded',
            'Employee pay rates to match industry averages',
            'Debits to always equal credits within each account',
        ],
        correctAnswer: 0,
        explanation: 'The matching principle is a fundamental accounting concept: expenses (including wages) must be recognized in the same period as the revenues they help generate. This provides an accurate picture of profitability for each period. For payroll, this means accruing wages earned in December even if paid in January.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Accounting',
        stem: 'On the balance sheet, accrued payroll is classified as:',
        options: [
            'A current liability',
            'A long-term liability',
            'An asset',
            'Shareholders\' equity',
        ],
        correctAnswer: 0,
        explanation: 'Accrued payroll (wages earned but not yet paid) is a current liability — an obligation expected to be settled within one year (typically within the next pay period). Current liabilities include accrued wages, taxes payable, and benefits payable. Long-term liabilities are due beyond one year. Payroll is an expense, not an asset or equity item.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Accounting',
        stem: 'A compound journal entry in payroll:',
        options: [
            'Contains more than two line items — multiple debits and/or credits in a single entry',
            'Involves only one debit and one credit',
            'Is an entry that has been posted twice by mistake',
            'Records only employer taxes, not employee deductions',
        ],
        correctAnswer: 0,
        explanation: 'Payroll journal entries are almost always compound entries because they involve multiple debits (wage expense, employer tax expense) and multiple credits (various tax liabilities, deduction liabilities, cash). A simple entry has only one debit and one credit. Compound entries are standard in payroll accounting due to the many components involved.',
        difficulty: 'Easy',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Accounting',
        stem: 'Reconciling the general ledger payroll accounts involves:',
        options: [
            'Comparing GL account balances to payroll register totals, tax filings, and bank statements to identify and resolve differences',
            'Only verifying that the GL has been updated each pay period',
            'Checking that all employees are listed in the GL',
            'Ensuring the GL uses the correct font and formatting',
        ],
        correctAnswer: 0,
        explanation: 'GL reconciliation is a critical control that compares payroll-related account balances (wages expense, tax liabilities, benefit liabilities, cash) to source documents: payroll registers, tax returns (941, 940), bank statements, and vendor reports. Discrepancies are investigated and resolved to ensure accurate financial reporting.',
        difficulty: 'Medium',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Accounting',
        stem: 'When an employee repays an overpayment from a prior year, the accounting treatment is to:',
        options: [
            'Record the repayment based on the gross overpayment amount and adjust the appropriate tax liabilities',
            'Simply reduce the employee\'s current gross pay by the net overpayment amount',
            'Ignore the repayment since it occurred in a prior year',
            'Record it as revenue in the current year',
        ],
        correctAnswer: 0,
        explanation: 'Prior-year overpayment recovery requires careful accounting: the gross amount must be recovered, and tax adjustments depend on the year. Social Security and Medicare taxes can be adjusted if repaid in the same year, but prior-year repayments may require the employee to claim a credit on their tax return. A corrected W-2c may be needed for the prior year.',
        difficulty: 'Hard',
    },
    {
        examId: CPP_ID, type: 'mcq', domain: 'Accounting',
        stem: 'The income statement reflects payroll costs as:',
        options: [
            'Operating expenses that reduce net income for the period',
            'Assets that increase the company\'s net worth',
            'Cash inflows from employee contributions',
            'Long-term investments in human capital',
        ],
        correctAnswer: 0,
        explanation: 'Payroll costs (wages, employer taxes, benefits) appear on the income statement as operating expenses, directly reducing net income. Higher payroll costs lower profitability. On the balance sheet, any unpaid payroll obligations appear as current liabilities. Payroll is not an asset, cash inflow, or investment from an accounting perspective.',
        difficulty: 'Easy',
    },
];

async function main() {
    console.log(`Seeding ${questions.length} CPP questions...`);

    const batch = db.batch();
    for (const q of questions) {
        const ref = db.collection('questions').doc();
        batch.set(ref, {
            ...q,
            isPublished: true,
            createdAt: admin.firestore.FieldValue.serverTimestamp(),
            source: 'seed-cpp-v1',
        });
        console.log(`  + ${q.domain} | ${q.stem.substring(0, 60)}...`);
    }

    await batch.commit();
    console.log(`\nDone! ${questions.length} CPP questions added.`);
    process.exit(0);
}

main().catch(e => { console.error(e); process.exit(1); });
